version: '3.4'

services:
  customerdb:
    container_name: customerdb
    environment:
      SA_PASSWORD: "Admin@12345"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1401:1433"

  orderdb:
    container_name: orderdb
    environment:
      SA_PASSWORD: "Admin@12345"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1402:1433"

  DeliveryPartnerDb:
    container_name: DeliveryPartnerDb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  FoodPartnerDb:
    container_name: FoodPartnerDb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  customer.api:
    container_name: customer.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:CustomerConnectionString=Server=host.docker.internal,1401;Database=customerdb;User Id=sa;Password=Admin@12345"
    depends_on:
      - customerdb        
    ports:
      - "8000:80"


  deliverypartner.api:
    container_name: deliverypartner.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://DeliveryPartnerDb:27017"
    depends_on:
      - DeliveryPartnerDb
    ports:
      - "8001:80"


  foodpartner.api:
    container_name: foodpartner.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://FoodPartnerDb:27018"
    depends_on:
      - FoodPartnerDb
    ports:
      - "8002:80"


  foodordering.api:
    container_name: foodordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnectionString=Server=host.docker.internal,1402;Database=orderdb;User Id=sa;Password=Admin@12345"
    depends_on:
      - orderdb
    ports:
      - "8003:80"

